### PR TITLE
Update browser drivers

### PR DESCRIPTION
**Pull request by lazargeorge**

### CODE REVIEW

**Review by killerboot — COMMENTED** [review]
Are you sure you want to commit binary files to git?
How do I know the version of the driver committed?

**Comment by lazargeorge** [comment]
I am replacing the previous binary files drivers, using their default set names. The drivers are ChromeDriver 78.0.3904.70 and geckodriver-v0.26.0. I should probably add a readme to specify the versions indeed. Is this ok?

**Comment by killerboot** [comment]
No, placing binaries in git is bad practice.
Every project that uses tas utility will have to download 10+ Mb regardless if it uses the drivers or not. Please use Nexus for artefacts.

**Comment by lazargeorge** [comment]
I've found a workaround by adding the drivers on TSE project. We can close this pull request, in the next release we can delete the drivers and update the documentation

**Comment by killerboot** [comment]
Sounds good, thanks.

**Pull request closed without merging**
